CREATE TABLE IF NOT EXISTS book (
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     text NOT NULL,
    author    text NOT NULL,
    year      int  NOT NULL,
    publisher text NOT NULL,
    toc       xml  NOT NULL DEFAULT '<toc/>'::xml
);

CREATE OR REPLACE FUNCTION book_select()
RETURNS SETOF book
LANGUAGE sql
AS $$
    SELECT * FROM book ORDER BY id;
$$;

CREATE OR REPLACE FUNCTION book_select_by_id(p_id int)
RETURNS SETOF book
LANGUAGE sql
AS $$
    SELECT * FROM book WHERE id = p_id;
$$;

CREATE OR REPLACE FUNCTION book_insert(
    p_title text,
    p_author text,
    p_year int,
    p_publisher text,
    p_toc xml
)
RETURNS SETOF book
LANGUAGE sql
AS $$
    INSERT INTO book (title, author, year, publisher, toc)
    VALUES (p_title, p_author, p_year, p_publisher, p_toc)
    RETURNING *;
$$;

CREATE OR REPLACE FUNCTION book_update(
    p_id int,
    p_title text,
    p_author text,
    p_year int,
    p_publisher text,
    p_toc xml
)
RETURNS SETOF book
LANGUAGE sql
AS $$
    UPDATE book
    SET title = p_title,
        author = p_author,
        year = p_year,
        publisher = p_publisher,
        toc = p_toc
    WHERE id = p_id
    RETURNING *;
$$;

CREATE OR REPLACE FUNCTION book_delete(p_id int)
RETURNS void
LANGUAGE sql
AS $$
    DELETE FROM book WHERE id = p_id;
$$;

CREATE OR REPLACE FUNCTION book_toc_headings(p_id int)
RETURNS TABLE (heading text)
LANGUAGE sql
AS $$
    SELECT t.heading
    FROM book b,
         xmltable(
             '//h2' PASSING b.toc
             COLUMNS heading text PATH '.'
         ) AS t
    WHERE b.id = p_id;
$$;

CREATE OR REPLACE FUNCTION book_toc_all_headings()
RETURNS TABLE (id int, title text, heading text)
LANGUAGE sql
AS $$
    SELECT b.id, b.title, t.heading
    FROM book b,
         xmltable(
             '//h2' PASSING b.toc
             COLUMNS heading text PATH '.'
         ) AS t
    ORDER BY b.id;
$$;
